---
- name: Backup Aruba CX Switch Configuration
  hosts: foobar-switch
  gather_facts: yes
  collections:
    - arubanetworks.aoscx
  
  tasks:
    - name: Get running configuration
      aoscx_command:
        commands:
          - show running-config
      register: running_config
    
    - name: Create backup directory
      file:
        path: "/tmp/backups"
        state: directory
      delegate_to: localhost
    
    - name: Save configuration to mounted backup directory
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/tmp/backups/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
      delegate_to: localhost
    
    - name: Display success message
      debug:
        msg: "Configuration saved to /home/traversa/awx-backups/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt on host"

    - name: Debug execution environment details
  shell: |
    echo "=== Hostname ==="
    hostname
    echo "=== Current directory ==="
    pwd
    echo "=== Mount points ==="
    mount | grep backup || echo "No backup mounts"
    echo "=== /tmp contents ==="
    ls -la /tmp/
    echo "=== Process list ==="
    ps aux | head -5
  register: debug_info
  delegate_to: localhost

- name: Show debug info
  debug:
    var: debug_info.stdout_lines
