---
- name: Backup Aruba CX Switch Configuration
  hosts: foobar-switch
  gather_facts: yes
  collections:
    - arubanetworks.aoscx
  
  tasks:
    - name: Get running configuration
      aoscx_command:
        commands:
          - show running-config
      register: running_config
    
    - name: Save configuration to persistent location
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/var/lib/awx/projects/_13__network_automation_playbooks/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
      delegate_to: localhost
    
    - name: Display file location
      debug:
        msg: "Configuration saved to /var/lib/awx/projects/_13__network_automation_playbooks/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
