---
- name: Backup Aruba CX Switch Configuration
  hosts: all
  gather_facts: no
  collections:
    - arubanetworks.aoscx
  
  tasks:
    - name: Get running configuration
      aoscx_command:
        commands:
          - show running-config
      register: running_config
    
    - name: Save configuration to file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/var/lib/awx/projects/switch-backups/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
      delegate_to: localhost
    
    - name: Display backup location
      debug:
        msg: "Configuration saved to /var/lib/awx/projects/switch-backups/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
