---
- name: Backup Aruba CX Switch Configuration
  hosts: foobar-switch
  gather_facts: yes
  collections:
    - arubanetworks.aoscx
  
  tasks:
    - name: Get running configuration
      aoscx_command:
        commands:
          - show running-config
      register: running_config
    
    - name: Save configuration to mounted backup directory
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/tmp/backups/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}-config.txt"
      delegate_to: localhost
